name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYmZlMGQ3NTItMDQ3MS00YTM2LWJjOTMtMGRiM2RiMzAyNzUxIiwidGVuYW50X2lkIjoiODdjNDc1MGU4ZGE3MzNmYmYzMDc5MzVkNDQzODJiNTA2NTJkMDczNzM5N2YxMDBhNzE2MjU0ZDhmMWU3YzJkYiIsImludGVybmFsX3NlY3JldCI6Ijc0ODAzM2UxLTRkZTctNGYyZi05YWIzLWFhZGZkNDcyNmU3YSJ9.sXn3pa3b6U9wFv_KqmWOaRto20aZChcRbt6zwztNvrA"
JWT_SECRET="navneet"