name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="1MGU4ZGE3MzNmYmYzMDc5MzVkNDQzODJiNTA2NTJkMDczNzM5N2YxMDBhNzE2MjU0ZDhmMWU3YzJkYiIsImludGVybmFsX3NlY3JldCI6Ijc0ODAzM2UxLTRkZTctNGYyZi05YWIzLWFhZGZkNDcyNmU3YSJ9.1bl4KKwEOG1y5SZxsuPo1-t-ZbFCMlKXUcmc29jMQys"
JWT_SECRET="navneetlkasdf"
