name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiN2RiNDEyODUtYmJkYi00ZDU0LWJiYjQtOTBlMjgyZDA3NTA5IiwidGVuYW50X2lkIjoiODdjNDc1MGU4ZGE3MzNmYmYzMDc5MzVkNDQzODJiNTA2NTJkMDczNzM5N2YxMDBhNzE2MjU0ZDhmMWU3YzJkYiIsImludGVybmFsX3NlY3JldCI6Ijc0ODAzM2UxLTRkZTctNGYyZi05YWIzLWFhZGZkNDcyNmU3YSJ9.kHRXgoEI2MXu0QC9JOc50tibPEP8PG8sJjJvuA4eLBo"
JWT_SECRET="navneet"